# Generated by Django 4.2.1 on 2023-08-30 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('woke_up', models.DateTimeField(default=django.utils.timezone.now)),
                ('slept', models.DateTimeField(default=django.utils.timezone.now)),
                ('gym', models.BooleanField(default=False)),
                ('bh_noti', models.BooleanField(default=False)),
                ('bh_post', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
