# Generated by Django 4.2.1 on 2023-08-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_dailyanalytics_slept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyanalytics',
            name='slept',
            field=models.DateTimeField(null=True),
        ),
    ]
