# Generated by Django 4.2.1 on 2023-08-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_dailyanalytics_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyanalytics',
            name='yt',
            field=models.BooleanField(default=False),
        ),
    ]
